### ISSUE TITLE
Some warning msgs

### ISSUE THREAD

**Issue by zlatnaspirala** [dabeschte/npybvh#3]
I got pose view after closing window i got two new windows in last i got nice bvh moving parts.
Is it normal regime or i miss something ?
Maybe after resolving warnings i will got different flow of app. 

I have some idea to learn about bvh procedure and to rewrite in JS. This project looks perfect. 

Logs 

```py
python bvh.py
Traceback (most recent call last):
  File "G:\web_server\xampp\htdocs\PRIVATE_SERVER\PYTHON\cross-k\cross-k\kivy_venv\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "G:\web_server\xampp\htdocs\PRIVATE_SERVER\PYTHON\cross-k\cross-k\kivy_venv\lib\site-packages\matplotlib\backend_bases.py", line 3279, in <lambda>     
    "close_event", lambda e: manager.destroy())
  File "G:\web_server\xampp\htdocs\PRIVATE_SERVER\PYTHON\cross-k\cross-k\kivy_venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 495, in destroy    self._window_dpi.trace_remove('write', self._window_dpi_cbname)
  File "C:\Python39\lib\tkinter\__init__.py", line 430, in trace_remove
    self._tk.deletecommand(cbname)
_tkinter.TclError: can't delete Tcl command
Traceback (most recent call last):
  File "G:\web_server\xampp\htdocs\PRIVATE_SERVER\PYTHON\cross-k\cross-k\kivy_venv\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process      
    func(*args, **kwargs)
  File "G:\web_server\xampp\htdocs\PRIVATE_SERVER\PYTHON\cross-k\cross-k\kivy_venv\lib\site-packages\matplotlib\backend_bases.py", line 3279, in <lambda>     
    "close_event", lambda e: manager.destroy())
  File "G:\web_server\xampp\htdocs\PRIVATE_SERVER\PYTHON\cross-k\cross-k\kivy_venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 495, in destroy    self._window_dpi.trace_remove('write', self._window_dpi_cbname)
  File "C:\Python39\lib\tkinter\__init__.py", line 430, in trace_remove
    self._tk.deletecommand(cbname)
_tkinter.TclError: can't delete Tcl command
Hips: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
LHipJoint: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
LeftUpLeg: p=[37.2311396  13.21075999  4.44465999], r=[  0.  -0. -21.]
LeftLeg: p=[37.12349505  7.04378875  4.44465999], r=[  0.  -0. -21.]
LeftFoot: p=[ 3.70000895e+01 -2.61488833e-02  4.44465999e+00], r=[  0.  -0. -21.]
LeftToeBase: p=[36.99768762 -0.16391876  6.10694999], r=[  0.  -0. -21.]
LeftToeBase_end: p=[36.99768762 -0.16391876  6.95861999], r=[ 0.         -0.         -0.36651914]
RHipJoint: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
RightUpLeg: p=[30.9525196  13.21075999  4.44465999], r=[ 0. -0. 21.]
RightLeg: p=[31.06223474  6.92535442  4.44465999], r=[ 0. -0. 21.]
RightFoot: p=[31.18189392  0.0701893   4.44465999], r=[ 0. -0. 21.]
RightToeBase: p=[31.1863317  -0.18411085  5.99688999], r=[ 0. -0. 21.]
RightToeBase_end: p=[31.1863317  -0.18411085  6.79969999], r=[ 0.         -0.          0.36651914]
LowerBack: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
Spine: p=[34.1053196  16.74816999  2.78184999], r=[ 0. -0.  0.]
Spine1: p=[34.1265396  18.63482999  2.97890999], r=[ 0. -0.  0.]
Neck: p=[34.1265396  18.63482999  2.97890999], r=[-16.  -0.   0.]
Neck1: p=[34.1097096  20.40217834  2.55434587], r=[ 5. -0.  0.]
Head: p=[34.1178596  22.17725991  2.23082333], r=[16. -0.  0.]
Head_end: p=[34.1158196  23.98520532  2.57308943], r=[ 0.27925268 -0.          0.        ]
LeftShoulder: p=[34.1265396  18.63482999  2.97890999], r=[ 0. -0.  0.]
LeftArm: p=[37.5113596  20.05015999  3.17692999], r=[ 0. -0. -8.]
LeftForeArm: p=[41.79636836 19.44794128  3.17692999], r=[ 0. -0. -8.]
LeftHand: p=[45.0502605  18.99063657  3.17692999], r=[ 0. -0. -8.]
LeftFingerBase: p=[45.0502605  18.99063657  3.17692999], r=[ 0. -0. -8.]
LeftHandIndex1: p=[45.47920502 18.93035235  3.17692999], r=[ 0. -0. -8.]
LeftHandIndex1_end: p=[45.82502643 18.88175032  3.17692999], r=[ 0.         -0.         -0.13962634]
LThumb: p=[45.0502605  18.99063657  3.17692999], r=[ 0. -0. -8.]
LThumb_end: p=[45.40136995 18.94129135  3.53148999], r=[ 0.         -0.         -0.13962634]
RightShoulder: p=[34.1265396  18.63482999  2.97890999], r=[ 0. -0.  0.]
RightArm: p=[31.0292896  20.26340999  2.83746999], r=[ 0. -0.  8.]
RightForeArm: p=[26.7800097  19.66621265  2.83746999], r=[ 0. -0.  8.]
RightHand: p=[23.58421659 19.21707322  2.83746999], r=[ 0. -0.  8.]
RightFingerBase: p=[23.58421659 19.21707322  2.83746999], r=[ 0. -0.  8.]
RightHandIndex1: p=[23.04588706 19.14141594  2.83746999], r=[ 0. -0.  8.]
RightHandIndex1_end: p=[22.61187238 19.08041915  2.83746999], r=[ 0.         -0.          0.13962634]
RThumb: p=[23.58421659 19.21707322  2.83746999], r=[ 0. -0.  8.]
RThumb_end: p=[23.14357701 19.15514536  3.28243999], r=[ 0.         -0.          0.13962634]

G:\web_server\xampp\htdocs\PRIVATE_SERVER\python-bvh\npybvh>python bvh.py
Hips: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
LHipJoint: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
LeftUpLeg: p=[37.2311396  13.21075999  4.44465999], r=[  0.  -0. -21.]
LeftLeg: p=[37.12349505  7.04378875  4.44465999], r=[  0.  -0. -21.]
LeftFoot: p=[ 3.70000895e+01 -2.61488833e-02  4.44465999e+00], r=[  0.  -0. -21.]
LeftToeBase: p=[36.99768762 -0.16391876  6.10694999], r=[  0.  -0. -21.]
LeftToeBase_end: p=[36.99768762 -0.16391876  6.95861999], r=[ 0.         -0.         -0.36651914]
RHipJoint: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
RightUpLeg: p=[30.9525196  13.21075999  4.44465999], r=[ 0. -0. 21.]
RightLeg: p=[31.06223474  6.92535442  4.44465999], r=[ 0. -0. 21.]
RightFoot: p=[31.18189392  0.0701893   4.44465999], r=[ 0. -0. 21.]
RightToeBase: p=[31.1863317  -0.18411085  5.99688999], r=[ 0. -0. 21.]
RightToeBase_end: p=[31.1863317  -0.18411085  6.79969999], r=[ 0.         -0.          0.36651914]
LowerBack: p=[34.0923996  14.78299999  2.94679999], r=[ 0. -0.  0.]
Spine: p=[34.1053196  16.74816999  2.78184999], r=[ 0. -0.  0.]
Spine1: p=[34.1265396  18.63482999  2.97890999], r=[ 0. -0.  0.]
Neck: p=[34.1265396  18.63482999  2.97890999], r=[-16.  -0.   0.]
Neck1: p=[34.1097096  20.40217834  2.55434587], r=[ 5. -0.  0.]
Head: p=[34.1178596  22.17725991  2.23082333], r=[16. -0.  0.]
Head_end: p=[34.1158196  23.98520532  2.57308943], r=[ 0.27925268 -0.          0.        ]
LeftShoulder: p=[34.1265396  18.63482999  2.97890999], r=[ 0. -0.  0.]
LeftArm: p=[37.5113596  20.05015999  3.17692999], r=[ 0. -0. -8.]
LeftForeArm: p=[41.79636836 19.44794128  3.17692999], r=[ 0. -0. -8.]
LeftHand: p=[45.0502605  18.99063657  3.17692999], r=[ 0. -0. -8.]
LeftFingerBase: p=[45.0502605  18.99063657  3.17692999], r=[ 0. -0. -8.]
LeftHandIndex1: p=[45.47920502 18.93035235  3.17692999], r=[ 0. -0. -8.]
LeftHandIndex1_end: p=[45.82502643 18.88175032  3.17692999], r=[ 0.         -0.         -0.13962634]
LThumb: p=[45.0502605  18.99063657  3.17692999], r=[ 0. -0. -8.]
LThumb_end: p=[45.40136995 18.94129135  3.53148999], r=[ 0.         -0.         -0.13962634]
RightShoulder: p=[34.1265396  18.63482999  2.97890999], r=[ 0. -0.  0.]
RightArm: p=[31.0292896  20.26340999  2.83746999], r=[ 0. -0.  8.]
RightForeArm: p=[26.7800097  19.66621265  2.83746999], r=[ 0. -0.  8.]
RightHand: p=[23.58421659 19.21707322  2.83746999], r=[ 0. -0.  8.]
RightFingerBase: p=[23.58421659 19.21707322  2.83746999], r=[ 0. -0.  8.]
RightHandIndex1: p=[23.04588706 19.14141594  2.83746999], r=[ 0. -0.  8.]
RightHandIndex1_end: p=[22.61187238 19.08041915  2.83746999], r=[ 0.         -0.          0.13962634]
RThumb: p=[23.58421659 19.21707322  2.83746999], r=[ 0. -0.  8.]
RThumb_end: p=[23.14357701 19.15514536  3.28243999], r=[ 0.         -0.          0.13962634]
```

**Comment by dabeschte** [comment]
Hi!
Yes, that is normal. read the __main__ function at the bottom of bvh.py and you'll see what happens. [link](https://github.com/dabeschte/npybvh/blob/add42e2ca57a17a8895a115c121385452b62d9e6/bvh.py#L261)

this is just an example file that does some example visualizations of the skeleton, a single frame and the entire sequence.

**Comment by zlatnaspirala** [comment]
Thanks for great project! I will give special credit.
